// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.startupExperimentPrefs.network.http.http3.retry_different_ip_family", false);
user_pref("app.normandy.user_id", "8e211d05-7b57-4fb0-a07d-44743988884c");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1692728838);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1692728837);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.cache.disk.capacity", 0);
user_pref("browser.cache.disk.enable", false);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.enabled", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.contentblocking.category", "strict");
user_pref("browser.contextual-services.contextId", "{8baf703e-49de-4caf-8b04-9bc493e4b1fc}");
user_pref("browser.ctrlTab.previews", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1692728836);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 137);
user_pref("browser.newtabpage.activity-stream.impressionId", "{5088f987-82c3-42f6-affe-4ca32d8ca0bc}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1692728837);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1692728839348");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1692750439348");
user_pref("browser.search.region", "IN");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1692728836");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20230816233310");
user_pref("browser.startup.homepage_override.mstone", "116.0.3");
user_pref("browser.startup.lastColdStartupCheck", 1692728836);
user_pref("browser.tabs.drawInTitlebar", false);
user_pref("browser.tabs.inTitlebar", 0);
user_pref("browser.topsites.contile.cacheValidFor", 10797);
user_pref("browser.topsites.contile.cachedTiles", "[{\"id\":74357,\"name\":\"Amazon\",\"url\":\"https://www.amazon.in/?tag=admpdesktopin-21&ref=pd_sl_82a1e1eeaca74aea6b346218abeddf1bf6cba7481393ddbc605818e1&mfadid=adm\",\"click_url\":\"https://bridge.sfo1.ap01.net/ctp?version=16.0.0&key=1692728354400900000.1&ci=1692728354443.12791&ctag=pd_sl_82a1e1eeaca74aea6b346218abeddf1bf6cba7481393ddbc605818e1\",\"image_url\":\"https://contile-images.services.mozilla.com/obgoOYObjIFea_bXuT6L4LbBJ8j425AD87S1HMD3BWg.9991.jpg\",\"image_size\":200,\"impression_url\":\"https://imp.mt48.net/static?id=7RHzfOIXjFEYsBdvIpkX4QqY4Z8afZDk4pbW1CbWfpbW7ReNxR3UIG8zInwYIFIVs9eYiGINHrwkiFXwxYIZjF8XgClWfC2X7R4dHQ8zJnErj%3DcO7R4dHQfz4Z2Z4CxnHG3Z5FwqgCfX1p8d4Cxr1BINI9HuiF2z4Z2Z4CxnHmcux%3DcvImauiF2zfQlXfplZ7ncqIr7VjGbuiF2zfCfdfC2X4QDnj9wWIBdvIpkY7R4TJr2uJREuHnEYgClnHr7wHG3vjnDuiF2z4Z2Z7ReTHF4wJFEUjtdvIpkXfpbr\"},{\"id\":73588,\"name\":\"Trivago\",\"url\":\"https://www.trivago.in/?cip=91030227040712&cip_tc=12891-101-101_privacy_1692728354400900000&cip_ext_id=1692728354400900000&mfadid=adm\",\"click_url\":\"https://bridge.sfo1.admarketplace.net/ctp?version=16.0.0&key=1692728354400900000.2&ci=1692728354443.12791&ctag=1692728354400900000\",\"image_url\":\"https://contile-images.services.mozilla.com/Eqfx-dXqpGIFV5Tmm1gv8XVA8ATij7ohWbjS9ic6ZsA.15089.jpg\",\"image_size\":200,\"impression_url\":\"https://imp.mt48.net/static?id=7RHzfOIXjFEYsBdvIpkX4QqY4Z8afZDk4pbW1CbWfpbW7ReNxR3UIG8zInwYIFIVs9eYiGINHrwkiFXwxYIZjF8XgClWfC2X7R4dHQ8zJnErj%3DcO7R4dHQfz4Zfd1pLnHG3Z5FwqgCfX1p8d4Cxr1BINI9HuiF2z4Zfd1pLnHmcux%3DcvImauiF2zfQl%2B1pqZ7ncqIr7VjGbuiF2zfCDkfCxZfpxnj9wWIBdvIpkY7R4TJr2uJREuHnEYgC8nHr7wHG3vjnDuiF2z1pbr7ReTHF4wJFEUjtdvIpkXfpbr\"}]");
user_pref("browser.topsites.contile.lastFetch", 1692728837);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":19,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1692728837095");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "116.0.3");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "IN");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "abb7b17c75d84c38b1f9194ca593befe");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230816233310");
user_pref("extensions.lastAppVersion", "116.0.3");
user_pref("extensions.lastPlatformVersion", "116.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"806ea860-a7f7-4d52-9e8e-f685fffd68c1\",\"pictureinpicture@mozilla.org\":\"cdacc028-7799-40d1-ba92-56282afd4b82\",\"screenshots@mozilla.org\":\"3f84ee89-f6b0-4232-b259-4f7ca8be8c2c\",\"webcompat-reporter@mozilla.org\":\"e4b31274-74c2-4bb9-aa9f-259a21350c32\",\"webcompat@mozilla.org\":\"bbeb1041-3bad-44b9-b146-967131689006\",\"default-theme@mozilla.org\":\"6e33aa15-2eb6-45a6-99be-01473ed4599b\",\"addons-search-detection@mozilla.com\":\"9d65fa51-6a87-4c64-8bfb-9fc896b3e369\",\"google@search.mozilla.org\":\"4a8333f7-b972-4913-8eae-5e9f446a75b4\",\"wikipedia@search.mozilla.org\":\"b00a647a-a308-4706-83e6-7cd77fb273b0\",\"bing@search.mozilla.org\":\"3c7c7b35-979c-425f-9c96-1825887e8361\",\"ddg@search.mozilla.org\":\"6ed6715f-9c45-40e9-b41e-2d2f77b4bb53\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.http.referer.disallowCrossSiteRelaxingDefault.top_navigation", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("plugin.state.flash", 2);
user_pref("privacy.annotate_channels.strict_list.enabled", true);
user_pref("privacy.partition.network_state.ocsp_cache", true);
user_pref("privacy.query_stripping.enabled", true);
user_pref("privacy.query_stripping.enabled.pbmode", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.trackingprotection.emailtracking.enabled", true);
user_pref("privacy.trackingprotection.enabled", true);
user_pref("privacy.trackingprotection.socialtracking.enabled", true);
user_pref("security.sandbox.content.tempDirSuffix", "36122d5e-a921-46d4-ab66-66d83d9eafc7");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("toolkit.startup.last_success", 1692728835);
user_pref("toolkit.telemetry.cachedClientID", "e69207c1-1c24-4d3e-866a-c2ad1aa48a88");
user_pref("toolkit.telemetry.previousBuildID", "20230816233310");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
