###################################################
#               _                       _         #
#              (_)                     (_)        #
#   _ __  _ __  _ ___  __ _ _ __ __ _   _ _ __    #
#  | '_ \| '_ \| / __|/ _` | '__/ _` | | | '_ \   #
#  | | | | | | | \__ \ (_| | | | (_| |_| | | | |  #
#  |_| |_|_| |_|_|___/\__,_|_|  \__, (_)_|_| |_|  #
#                                __/ |            #
#                               |___/             #
###################################################


live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#a1a0a1"
blue = "#BFBDC4"
cyan = "#CFCBD0"
green = "#AEABB5"
magenta = "#C3BCC5"
red = "#A29CA7"
white = "#e7e5e6"
yellow = "#BBB9C3"

[colors.cursor]
cursor = "#cad5ff"
text = "#cad5ff"

[colors.normal]
black = "#080D13"
blue = "#BFBDC4"
cyan = "#CFCBD0"
green = "#AEABB5"
magenta = "#C3BCC5"
red = "#A29CA7"
white = "#e7e5e6"
yellow = "#BBB9C3"

[colors.primary]
background = "#000000"
foreground = "#cad5ff"

[font]
size = 12

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "BoldItalic"

[font.italic]
family = "JetBrains Mono"
style = "MediumItalic"

[font.normal]
family = "JetBrains Mono"
style = "Medium"

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 0.85

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 20
y = 20
