[window]
padding = { x = 10, y = 10 }
opacity = 0.6
blur = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 12

[colors.primary]
background = "#0c0c09"
foreground = "#eae5e1"

[colors.normal]
black = '#8d9185'
red = '#b1b69d'
green = '#cab38e'
yellow = '#d4c8b2'
blue = '#d1c3b4'
magenta = '#d3c7ba'
cyan = '#ded6ce'
white = '#eae5e1'

[colors.bright]
black = '#b9b6af'
red = '#b1b69d'
green = '#cab38e'
yellow = '#d4c8b2'
blue = '#d1c3b4'
magenta = '#d3c7ba'
cyan = '#ded6ce'
white = '#eae5e1'
